### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shehzadkhawar** [jbenner-radham/rfc-to-bib#1]
Installation was flawless. But I got this during usage:

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src/rfc-template.bib'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/rfc-to-bib/src/app.js:37:30)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

Any ideas?

**Comment by jbenner-radham** [comment]
Thanks for the error report! After a quick poke around I believe I see the issue, I'll try and get it patched and have a new release out tonight.

**Comment by jbenner-radham** [comment]
Fixed and published in release `0.1.3`.
